### ISSUE TITLE
Identify and fix issues related to adding Puerto Rico

### ISSUE THREAD

**Issue by maheese** [USEPA/power-profiler#52]

**Comment by ibarra-michelle** [comment]
- [ ] When PRMS (Puerto Rico) is selected in the eGRID Subregion dropdown, the "Or use the national average electricity use" link doesn't work since PRMS is not currently associated with an eGRID Region (see the file, add_egrid_data.py, lines 36-40 - lists for checking whether subregion is interconnect with power grid). Possible options for addressing this are:

- Option 1: Add PRMS into a eGRID Region.
- Option 2: Add text stating "we're unable to use the national average electricity use" feature for PRMS.
